version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cr3dentials-deploy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4rg5tlr4r4ls"
s3_prefix = "cr3dentials-deploy"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
