AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-nodejs18.x
  Sample SAM Template for lambda-nodejs18.x

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CreateInvoiceFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: create-invoice/
      Handler: app.createInvoice
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        CreateInvoice:
          Type: Api
          Properties:
            Path: /invoices
            Method: post
        UpdateInvoice:
          Type: Api
          Properties:
            Path: /invoices
            Method: put

  PayInvoiceFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: pay-invoice/
      Handler: app.payInvoice
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        PayInvoice:
          Type: Api
          Properties:
            Path: /invoices/pay #/invoices/{invoiceId}/pay
            Method: post # Adjust the HTTP method (e.g., POST, PUT, PATCH) as needed

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  CreateInvoiceApi:
    Description: "API Gateway endpoint URL for CreateInvoice function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/invoices/"
  PayInvoiceApi:
    Description: "API Gateway endpoint URL for PayInvoice function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/invoices/{invoiceId}/pay"
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
